name: "OpenSSF Scorecard Monitoring"
on:
  # manual
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  scoring:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: OpenSSF Scorecard Monitor
        uses: ossf/scorecard-monitor@a3a9c4cfa0684480ec5f86fa178fc22c4394b69e # v2.0.0-beta8
        id: openssf-scorecard-monitor
        with:
          scope: .github/ossf-scorecard/scope.json
          database: .github/ossf-scorecard/database.json
          report: .github/ossf-scorecard/report.md
          auto-commit: false
          auto-push: false
          generate-issue: false
          report-tags-enabled: true
          issue-title: "OpenSSF Scorecard Report Updated!"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-request-in-parallel: 5
          discovery-enabled: true
          discovery-orgs: "chgl"

      - name: prettify the generated files
        run: |
          npx prettier@3.3.3 .github/ossf-scorecard/ --write

      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@b65137ca591da0b9f43bad7b24df13050ea45d1b # v1.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "docs: OpenSSF Scorecard Report Updated"
          title: OpenSSF Scorecard Report Updated
          body: "OpenSSF Scorecard Report Updated"
          assignees: ${{ github.actor }}
          labels: automation
          branch: automation/openssf-scorecard-report-updated
          update-pull-request-title-and-body: true
