name: "OpenSSF Scorecard Monitoring"
on:
  # manual
  workflow_dispatch: {}

permissions: read-all

jobs:
  scoring:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: OpenSSF Scorecard Monitor
        uses: ossf/scorecard-monitor@a3a9c4cfa0684480ec5f86fa178fc22c4394b69e # v2.0.0-beta8
        id: openssf-scorecard-monitor
        with:
          scope: .github/ossf-scorecard/scope.json
          database: .github/ossf-scorecard/database.json
          report: .github/ossf-scorecard/report.md
          auto-commit: false
          auto-push: false
          generate-issue: false
          report-tags-enabled: true
          issue-title: "OpenSSF Scorecard Report Updated!"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-request-in-parallel: 5
          discovery-enabled: true
          discovery-orgs: "chgl"

      - name: Print the scores
        run: |
          echo '${{ steps.openssf-scorecard-monitor.outputs.scores }}'

      - name: prettify the generated files
        run: |
          npx prettier@3.3.3 .github/ossf-scorecard/ --write

      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@86ec1766034c8173518f61d2075cc2a173fb8c97 # v1.9.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "docs: OpenSSF Scorecard Report Updated"
          title: OpenSSF Scorecard Report Updated
          body: "OpenSSF Scorecard Report Updated"
          assignees: ${{ github.actor }}
          labels: automation
          branch: automation/openssf-scorecard-report-updated
          update-pull-request-title-and-body: true
