name: "OpenSSF Scorecard Monitoring"
on:
  # manual
  workflow_dispatch: {}

# Permissions required to run this workflow (create issue and commit/push changes)
permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: none

jobs:
  scoring:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: OpenSSF Scorecard Monitor
        uses: ossf/scorecard-monitor@8551177324543b39670fe3c430012c946a937bd1 # v2.0.0-beta7
        id: openssf-scorecard-monitor
        with:
          scope: .github/ossf-scorecard/scope.json
          database: tools/ossf-scorecard/database.json
          report: tools/ossf-scorecard/report.md
          auto-commit: false
          auto-push: false
          generate-issue: true
          report-tags-enabled: true
          issue-title: "OpenSSF Scorecard Report Updated!"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-request-in-parallel: 5
          discovery-enabled: true
          discovery-orgs: "chgl"

      - name: Print the scores
        run: |
          echo '${{ steps.openssf-scorecard-monitor.outputs.scores }}'
    #   - name: Create Pull Request
    #     uses: gr2m/create-or-update-pull-request-action@77596e3166f328b24613f7082ab30bf2d93079d5
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       commit-message: "docs: OpenSSF Scorecard Report Updated"
    #       title: OpenSSF Scorecard Report Updated
    #       body: "OpenSSF Scorecard Report Updated. cc: @nodejs/security-wg"
    #       assignees: ${{ github.actor }}
    #       labels: security-wg-agenda
    #       branch: openssf-scorecard-report-updated
    #       update-pull-request-title-and-body: true
