name: Standard workflow for building a container image from a Dockerfile

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  # renovate: datasource=github-releases depName=aquasecurity/trivy
  TRIVY_VERSION: 0.60.0
  TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
  TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1

on:
  workflow_call:
    inputs:
      image:
        description: "Name of the image to build and push, including its registry but excluding any tags"
        required: false
        default: "ghcr.io/${{ github.repository }}"
        type: string
      build-context:
        description: "The directory containing the Containerfile used to build the image"
        required: false
        default: "."
        type: string
      enable-upload-image:
        description: "If enabled, upload the image as a build artifact"
        required: false
        default: true
        type: boolean
      enable-build-test-layer:
        description: "If enabled, builds a layer called `test` inside the Dockerfile. Useful for unit testing."
        required: false
        default: false
        type: boolean
      enable-upload-test-image:
        description: "If enabled, uploads the image built from the test layer as an artifact."
        required: false
        default: false
        type: boolean
      enable-trivy-scan:
        description: "If enabled, scan the image using trivy and publish a signed attestation"
        required: false
        default: true
        type: boolean
      trivy-ignore-unfixed:
        description: "Ignore unfixed/unfixable vulnerabilities in reports"
        required: false
        default: true
        type: boolean
      image-tags:
        description: "If set, overwrite the default image tags. See <https://github.com/docker/metadata-action?tab=readme-ov-file#tags-input> for the format and usage."
        required: false
        default: ""
        type: string
      platforms:
        description: "List of target platforms for build"
        required: false
        type: string
        default: |
          linux/amd64
    outputs:
      image-tags:
        value: ${{ jobs.build.outputs.image-tags }}
        description: "The built image tags"
      image-version:
        value: ${{ jobs.build.outputs.image-version }}
        description: "The built image version"
      image-meta-json:
        value: ${{ jobs.build.outputs.image-meta-json }}
        description: "The built image meta data in JSON format"
      image-digest:
        value: ${{ jobs.build.outputs.image-digest }}
        description: "The built image digest"
      test-image-tags:
        value: ${{ jobs.build.outputs.test-image-tags }}
        description: "The test image tags"
      test-image-meta-json:
        value: ${{ jobs.build.outputs.test-image-meta-json }}
        description: "The test image meta data in JSON format"
      test-image-digest:
        value: ${{ jobs.build.outputs.test-image-digest }}
        description: "The test image digest"
      test-image-version:
        value: ${{ jobs.build.outputs.test-image-version }}
        description: "The built image version"
      image-slug:
        value: ${{ jobs.build.outputs.image-slug }}
        description: "The name of the build image in slugified form. This is the name of the artifact where the image was uploaded to."
    secrets:
      github-token:
        description: "The GitHub workflow token used to push to ghcr.io. Also used by MegaLinter"
        required: true

jobs:
  build:
    name: build image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      # for uploading trivy scan results to security tab
      security-events: write
      # for the trivy PR comment
      pull-requests: write
    outputs:
      image-version: ${{ steps.image_meta.outputs.version }}
      image-tags: ${{ steps.image_meta.outputs.tags }}
      image-meta-json: ${{ steps.image_meta.outputs.json }}
      image-digest: ${{ steps.build.outputs.digest }}
      test-image-version: ${{ steps.tests_image_meta.outputs.version }}
      test-image-tags: ${{ steps.tests_image_meta.outputs.tags }}
      test-image-meta-json: ${{ steps.tests_image_meta.outputs.json }}
      test-image-digest: ${{ steps.build_test.outputs.digest }}
      image-slug: ${{ steps.slugify-image.outputs.slug }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      # <https://docs.docker.com/storage/containerd/>
      # via <https://github.com/docker/setup-buildx-action/issues/257>
      - name: Set up containerd image store
        shell: bash
        run: |
          [ -f /etc/docker/daemon.json ] || echo "{}" | sudo tee /etc/docker/daemon.json
          jq '. | .+{"features": {"containerd-snapshotter": true}}' /etc/docker/daemon.json > /tmp/docker-daemon-with-containerd.json
          sudo mv /tmp/docker-daemon-with-containerd.json /etc/docker/daemon.json
          cat /etc/docker/daemon.json
          sudo systemctl restart docker

          docker info -f '{{ .DriverStatus }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          # zizmor: runtime artifacts potentially vulnerable to a cache poisoning attack
          cache-binary: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Container image meta
        id: image_meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: |
            ${{ inputs.image }}
          tags: |
            ${{ inputs.image-tags }}

      - name: Container meta for the test image
        id: tests_image_meta
        if: ${{ inputs.enable-build-test-layer == true }}
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ${{ inputs.image }}-test

      # ran first to avoid pushing failing images when running on master.
      - name: Build unit test image layer
        if: ${{ inputs.enable-build-test-layer == true }}
        id: build_test
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: ${{ inputs.build-context }}
          push: false
          load: true
          outputs: type=oci,dest=./image-test.tar
          tags: ${{ steps.tests_image_meta.outputs.tags }}
          labels: ${{ steps.tests_image_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: test
          platforms: ${{ inputs.platforms }}

      - uses: rlespinasse/slugify-value@a4879db1eb3db9bbee01dca36f98a8236c2b8239 # v1.4.0
        id: slugify-image
        with:
          key: BUILD_IMAGE
          value: ${{ steps.image_meta.outputs.json && fromJson(steps.image_meta.outputs.json).tags[0] }}
          publish-env: false
          slug-maxlength: nolimit

      - name: Upload test image
        if: ${{ (inputs.enable-build-test-layer == true) && (inputs.enable-upload-test-image == true) }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ steps.slugify-image.outputs.slug }}-test
          path: |
            ${{ github.workspace }}/image-test.tar

      - name: Build and push image
        id: build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: ${{ inputs.build-context }}
          # when in a PR, save the image as a tar archive
          # this way, we can save it as an artifact in later steps
          # otherwise (on branch-push or releases), push the image to
          # the registry
          load: ${{ github.event_name == 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}
          outputs: type=oci,dest=./image.tar
          sbom: ${{ github.event_name != 'pull_request' }}
          provenance: ${{ github.event_name != 'pull_request' && 'mode=max' || false }}
          tags: ${{ steps.image_meta.outputs.tags }}
          labels: ${{ steps.image_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ inputs.platforms }}

      - name: Upload container image
        if: ${{ github.event_name == 'pull_request' && inputs.enable-upload-image == true }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ steps.slugify-image.outputs.slug }}
          path: |
            ${{ github.workspace }}/image.tar

      - name: display images
        run: |
          ls -lsa ${{ github.workspace }}
          docker image ls -a

      - name: install trivy
        run: |
          wget "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb"
          sudo dpkg -i "trivy_${TRIVY_VERSION}_Linux-64bit.deb"

      - name: Create Trivy vulnerability attestation
        if: ${{ inputs.enable-trivy-scan }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TRIVY_IGNORE_UNFIXED: ${{ inputs.trivy-ignore-unfixed }}
          IMAGE_TO_SCAN: ${{ fromJson(steps.image_meta.outputs.json).tags[0] }}
        run: |
          trivy image \
            --exit-code=0 \
            --format=cosign-vuln \
            --output=trivy-vuln-attestation.json \
            --ignore-unfixed="${TRIVY_IGNORE_UNFIXED}" \
            "${IMAGE_TO_SCAN}"

      - name: Upload image vulnerability attestation
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ inputs.enable-trivy-scan }}
        with:
          name: ${{ steps.slugify-image.outputs.slug }}-trivy-attestation
          path: |
            trivy-vuln-attestation.json

      - name: Download PR comment template
        if: ${{ inputs.enable-trivy-scan }}
        run: |
          curl -o trivy-pr-report.md.tpl https://raw.githubusercontent.com/miracum/.github/master/.github/trivy-pr-report.md.tpl

      - name: Run Trivy vulnerability scanner for PR comment
        if: ${{ github.event_name == 'pull_request' && inputs.enable-trivy-scan }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TRIVY_IGNORE_UNFIXED: ${{ inputs.trivy-ignore-unfixed }}
          IMAGE_TO_SCAN: ${{ fromJson(steps.image_meta.outputs.json).tags[0] }}
        run: |
          trivy image \
            --exit-code=0 \
            --format=template \
            --output=trivy-pr-report.md \
            --template="@trivy-pr-report.md.tpl" \
            --ignore-unfixed="${TRIVY_IGNORE_UNFIXED}" \
            "${IMAGE_TO_SCAN}"

      - name: Add trivy report PR comment
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        # when running from a fork, the CI token doesn't have enough permissions to create PR comments
        if: ${{ github.event_name == 'pull_request' && inputs.enable-trivy-scan && !github.event.pull_request.head.repo.fork }}
        with:
          recreate: true
          header: "trivy-report-comment-${{ steps.slugify-image.outputs.slug }}"
          path: trivy-pr-report.md

      - name: Generate SBOMs
        env:
          IMAGE_TO_SCAN: ${{ fromJson(steps.image_meta.outputs.json).tags[0] }}
          IMAGE_SLUG: ${{ steps.slugify-image.outputs.slug }}
        run: |
          mkdir -p sboms/
          trivy image --format cyclonedx -o "sboms/$IMAGE_SLUG-sbom.cdx.json" "$IMAGE_TO_SCAN"
          trivy image --format spdx-json -o "sboms/$IMAGE_SLUG-sbom.spdx.json" "$IMAGE_TO_SCAN"

      - name: Upload SBOMs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ steps.slugify-image.outputs.slug }}-sboms
          path: |
            ./sboms/

    # requires content: write access
    #   - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
    #     uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0
    #     if: ${{ github.event_name != 'pull_request' }}
    #     with:
    #       image-ref: ${{ fromJson(steps.image_meta.outputs.json).tags[0] }}
    #       format: "github"
    #       output: "dependency-results.sbom.json"
    #       github-pat: ${{ secrets.github-token }}

  image-provenance:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - build
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ inputs.image }}
      digest: ${{ needs.build.outputs.image-digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.github-token }}

  sign-image:
    name: sign image
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - build
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

      - name: Sign image
        env:
          IMAGE: "${{ inputs.image }}@${{ needs.build.outputs.image-digest }}"
        run: |
          echo "Signing '$IMAGE' using keyless approach"
          cosign sign --yes "${IMAGE}"

  attest-trivy-vulnerability-report:
    name: attest trivy vulnerability report
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request' && inputs.enable-trivy-scan }}
    needs:
      - build
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Download attestations
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: ${{ needs.build.outputs.image-slug }}-trivy-attestation
          path: /tmp

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

      - name: Attest image vulnerability report
        env:
          IMAGE: "${{ inputs.image }}@${{ needs.build.outputs.image-digest }}"
        run: |
          echo "Attest vulnerability report for '$IMAGE' using keyless approach"
          cosign attest --yes --type vuln --predicate /tmp/trivy-vuln-attestation.json "$IMAGE"

  upload-attestion-to-release:
    name: upload slsa attestations to release assets
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - image-provenance
      - build
    permissions:
      # to upload artifacts to the release
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

      - name: download attestation from image
        env:
          IMAGE: "${{ inputs.image }}@${{ needs.build.outputs.image-digest }}"
          IMAGE_SLUG: "${{ needs.build.outputs.image-slug }}"
        run: |
          cosign download attestation --output-file="$IMAGE_SLUG.intoto.jsonl" "$IMAGE"

      - name: upload assets to release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            *.intoto.jsonl

  upload-sbom-to-release:
    name: upload image SBOMs to release assets
    runs-on: ubuntu-24.04
    needs:
      - build
    permissions:
      # to upload artifacts to the release
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Download sboms
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: ${{ needs.build.outputs.image-slug }}-sboms
          path: ./sboms

      - name: Display structure of downloaded files
        run: ls -R .

      - name: upload assets to release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          fail_on_unmatched_files: true
          files: |
            ./sboms/*.json
